spring.application.name=springbootbackendauthrbac

# =========================
# DATABASE CONFIG
# =========================
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auth_rbac_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET:mySecretKeyForJwtTokenGenerationThatMustBeAtLeast256BitsLong2026}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# =========================
# SERVER
# =========================
server.port=${PORT:8080}
